#!/bin/bash

# Run all dotfiles installers
# Inspired by https://github.com/holman/dotfiles

set -e

cd "$(dirname $0)"/..

# find installers and run them iteratively
find . -name install.sh | while read installer; do sh -c "${installer}" ; done

